// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHqUQ7jk3oT2ebCTp5n9NL_pLh2PEmD7w',
    appId: '1:759910252228:web:6f3ae7be3e595393e5d391',
    messagingSenderId: '759910252228',
    projectId: 'charlie-1234',
    authDomain: 'charlie-1234.firebaseapp.com',
    storageBucket: 'charlie-1234.firebasestorage.app',
    databaseURL:'https://charlie-1234-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJIvPn-5KIaOU3l2q4NydBGXR5suOEnM',
    appId: '1:759910252228:android:6aa4141a58a55c6be5d391',
    messagingSenderId: '759910252228',
    projectId: 'charlie-1234',
    storageBucket: 'charlie-1234.firebasestorage.app',
    databaseURL:'https://charlie-1234-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7jom5U0D2Ywcfyz2IOQVPAdYwkpnwAJ8',
    appId: '1:759910252228:ios:ac2f986893c5cb95e5d391',
    messagingSenderId: '759910252228',
    projectId: 'charlie-1234',
    storageBucket: 'charlie-1234.firebasestorage.app',
    iosBundleId: 'com.example.charlie',
    databaseURL:'https://charlie-1234-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7jom5U0D2Ywcfyz2IOQVPAdYwkpnwAJ8',
    appId: '1:759910252228:ios:ac2f986893c5cb95e5d391',
    messagingSenderId: '759910252228',
    projectId: 'charlie-1234',
    storageBucket: 'charlie-1234.firebasestorage.app',
    iosBundleId: 'com.example.charlie',
    databaseURL:'https://charlie-1234-default-rtdb.europe-west1.firebasedatabase.app/',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHqUQ7jk3oT2ebCTp5n9NL_pLh2PEmD7w',
    appId: '1:759910252228:web:c1e12d78d7961d2fe5d391',
    messagingSenderId: '759910252228',
    projectId: 'charlie-1234',
    authDomain: 'charlie-1234.firebaseapp.com',
    storageBucket: 'charlie-1234.firebasestorage.app',
    databaseURL:'https://charlie-1234-default-rtdb.europe-west1.firebasedatabase.app/',
  );
}
